# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-07 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameDB',
            fields=[
                ('token', models.AutoField(primary_key=True, serialize=False)),
                ('board', models.CharField(default='eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee', max_length=64)),
                ('active_players', models.IntegerField(default=0)),
            ],
        ),
    ]
