# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-08 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Othello', '0002_gamedb_playerturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedb',
            name='timer',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='gamedb',
            name='board',
            field=models.CharField(default='0000000000000000000000000001200000021000000000000000000000000000', max_length=64),
        ),
    ]
